### ISSUE TITLE
& character is not shown

### ISSUE THREAD

**Issue by mo6** [zevv/termtekst#12]
On some pages (for example: NOS teletekst page 502: "S&P" financial index) the ampersand is not shown (taken as html coding probably)

**Comment by zevv** [comment]
No problem here, ampersand is displayed just fine. As I can not
reproduce, it's hard for me to debug, appreciated if some one else could
figure this one out.

**Comment by mo6** [comment]
Ah, seems like a Python 2.7 issue. When testing with Python 3, there's no problem. Forcing to use Python 3 now:

```
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/env python3
```

**Comment by zevv** [comment]
Good good. I just pushed a change that deprecates 2.7 and forces 3, so we should be good now.

Thanks
