### ISSUE TITLE
Feature Request: Option to skip character translation

### ISSUE THREAD

**Issue by mo6** [zevv/termtekst#19]
It would be nice to have an option to leave out the character translation (to braille characters) so the NOS Teletekst font can be used in the terminal.

NOS Teletekst font can be found here: https://cdn.nos.nl/assets/nos-symfony/bcea4a1/bundles/nossite/fonts/teletekst/Android_VeraMono.woff

**Comment by zevv** [comment]
Ah, nice, I didn't know this font was available.

So, the question now is: config file or command line argument?

--
:wq
^X^Cy^K^X^C^C^C^C
